# Generated by Django 5.1.7 on 2025-03-23 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='image',
            field=models.CharField(default='default.png', max_length=255),
        ),
    ]
